
/* sequence */
DROP SEQUENCE BOARD_SEQ;
DROP SEQUENCE MEMO_SEQ;
DROP SEQUENCE CATEGORY_SEQ;
DROP SEQUENCE BOARD_LIST_SEQ;
DROP SEQUENCE BOARD_TYPE_SEQ;

/* sequence */
CREATE SEQUENCE BOARD_SEQ INCREMENT BY 1;
CREATE SEQUENCE MEMO_SEQ INCREMENT BY 1; 
CREATE SEQUENCE CATEGORY_SEQ INCREMENT BY 1; 
CREATE SEQUENCE BOARD_LIST_SEQ INCREMENT BY 1; 
CREATE SEQUENCE BOARD_TYPE_SEQ INCREMENT BY 1; 

/* 카테고리 */
DROP TABLE CATEGORY 
	CASCADE CONSTRAINTS;

/* 게시판 */
DROP TABLE BOARD 
	CASCADE CONSTRAINTS;

/* 댓글 */
DROP TABLE MEMO 
	CASCADE CONSTRAINTS;

/* 게시판리스트 */
DROP TABLE BOARD_LIST 
	CASCADE CONSTRAINTS;

/* 회원 */
DROP TABLE MEMBER 
	CASCADE CONSTRAINTS;

/* 게시판타입 */
DROP TABLE BOARD_TYPE 
	CASCADE CONSTRAINTS;

/* 카테고리 */
CREATE TABLE CATEGORY (
	CCODE NUMBER NOT NULL, /* 새 컬럼 */
	NAME VARCHAR2(100) NOT NULL, /* 새 컬럼2 */
	STATE NUMBER DEFAULT 1 NOT NULL /* 새 컬럼3 */
);

CREATE UNIQUE INDEX PK_CATEGORY
	ON CATEGORY (
		CCODE ASC
	);

ALTER TABLE CATEGORY
	ADD
		CONSTRAINT PK_CATEGORY
		PRIMARY KEY (
			CCODE
		);

/* 게시판 */
CREATE TABLE BOARD (
	BSEQ NUMBER NOT NULL, /* 새 컬럼 */
	BCODE NUMBER NOT NULL, /* 새 컬럼5 */
	ID VARCHAR2(20) NOT NULL, /* 새 컬럼9 */
	TITLE VARCHAR2(100) NOT NULL, /* 새 컬럼2 */
	CONTENT VARCHAR2(1000), /* 새 컬럼3 */
	IMG VARCHAR2(100), /* 새 컬럼4 */
	HIT NUMBER, /* 새 컬럼7 */
	REGDATE DATE NOT NULL, /* 새 컬럼8 */
	NOTICE NUMBER DEFAULT 0 NOT NULL /* 새 컬럼6 */
);

CREATE UNIQUE INDEX PK_BOARD
	ON BOARD (
		BSEQ ASC
	);

ALTER TABLE BOARD
	ADD
		CONSTRAINT PK_BOARD
		PRIMARY KEY (
			BSEQ
		);

/* 댓글 */
CREATE TABLE MEMO (
	MSEQ NUMBER NOT NULL, /* 새 컬럼 */
	BSEQ NUMBER NOT NULL, /* 새 컬럼2 */
	ID VARCHAR2(20) NOT NULL, /* 새 컬럼4 */
	CONTENT VARCHAR2(500) NOT NULL, /* 새 컬럼3 */
	REGDATE DATE NOT NULL /* 새 컬럼5 */
);

CREATE UNIQUE INDEX PK_MEMO
	ON MEMO (
		MSEQ ASC
	);

ALTER TABLE MEMO
	ADD
		CONSTRAINT PK_MEMO
		PRIMARY KEY (
			MSEQ
		);

/* 게시판리스트 */
CREATE TABLE BOARD_LIST (
	BCODE NUMBER NOT NULL, /* 새 컬럼 */
	CCODE NUMBER NOT NULL, /* 새 컬럼3 */
	BTYPE NUMBER NOT NULL, /* 새 컬럼4 */
	NAME VARCHAR2(100) NOT NULL, /* 새 컬럼2 */
	ROLE NUMBER DEFAULT 1 NOT NULL, /* 새 컬럼5 */
	STATE NUMBER DEFAULT 1 NOT NULL /* 새 컬럼6 */
);

CREATE UNIQUE INDEX PK_BOARD_LIST
	ON BOARD_LIST (
		BCODE ASC
	);

ALTER TABLE BOARD_LIST
	ADD
		CONSTRAINT PK_BOARD_LIST
		PRIMARY KEY (
			BCODE
		);

/* 회원 */
CREATE TABLE MEMBER (
	ID VARCHAR2(20) NOT NULL, /* 새 컬럼 */
	PWD VARCHAR2(20) NOT NULL, /* 새 컬럼8 */
	NAME VARCHAR2(20) NOT NULL, /* 새 컬럼2 */
	GENDER NUMBER NOT NULL, /* 새 컬럼3 */
	BIRTH VARCHAR2(10) NOT NULL, /* 새 컬럼5 */
	PHONE VARCHAR2(15) NOT NULL, /* 새 컬럼6 */
	ROLE NUMBER DEFAULT 1 NOT NULL, /* 새 컬럼10 */
	REGDATE DATE NOT NULL, /* 새 컬럼11 */
	STATE NUMBER DEFAULT 1 NOT NULL /* 새 컬럼7 */
);

CREATE UNIQUE INDEX PK_MEMBER
	ON MEMBER (
		ID ASC
	);

ALTER TABLE MEMBER
	ADD
		CONSTRAINT PK_MEMBER
		PRIMARY KEY (
			ID
		);

/* 게시판타입 */
CREATE TABLE BOARD_TYPE (
	BTYPE NUMBER NOT NULL, /* 새 컬럼 */
	NAME VARCHAR2(100) NOT NULL, /* 새 컬럼2 */
	STATE NUMBER DEFAULT 1 NOT NULL /* 새 컬럼3 */
);

CREATE UNIQUE INDEX PK_BOARD_TYPE
	ON BOARD_TYPE (
		BTYPE ASC
	);

ALTER TABLE BOARD_TYPE
	ADD
		CONSTRAINT PK_BOARD_TYPE
		PRIMARY KEY (
			BTYPE
		);

ALTER TABLE BOARD
	ADD
		CONSTRAINT FK_BOARD_LIST_TO_BOARD
		FOREIGN KEY (
			BCODE
		)
		REFERENCES BOARD_LIST (
			BCODE
		);

ALTER TABLE BOARD
	ADD
		CONSTRAINT FK_MEMBER_TO_BOARD
		FOREIGN KEY (
			ID
		)
		REFERENCES MEMBER (
			ID
		);

ALTER TABLE MEMO
	ADD
		CONSTRAINT FK_BOARD_TO_MEMO
		FOREIGN KEY (
			BSEQ
		)
		REFERENCES BOARD (
			BSEQ
		);

ALTER TABLE MEMO
	ADD
		CONSTRAINT FK_MEMBER_TO_MEMO
		FOREIGN KEY (
			ID
		)
		REFERENCES MEMBER (
			ID
		);

ALTER TABLE BOARD_LIST
	ADD
		CONSTRAINT FK_CATEGORY_TO_BOARD_LIST
		FOREIGN KEY (
			CCODE
		)
		REFERENCES CATEGORY (
			CCODE
		);

ALTER TABLE BOARD_LIST
	ADD
		CONSTRAINT FK_BOARD_TYPE_TO_BOARD_LIST
		FOREIGN KEY (
			BTYPE
		)
		REFERENCES BOARD_TYPE (
			BTYPE
		);